### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Kakamanoel0** [Oen44/OTUIEditor#1]
Hello, I really liked the tool, but trying to compile, as I always got some errors, I don't know if it's my problems or my computer's, but I couldn't compile on windows 64 bits, couldn't you post it compiled already?

**Comment by Oen44** [comment]
It's not production ready, it's not usable at all.

**Comment by Kakamanoel0** [comment]
I get it, I'm really looking forward to using it, the project is a beauty.
